site :opscode
metadata
cookbook 'apt'
cookbook 'build-essential'
cookbook 'drush', git: 'https://github.com/msonnabaum/chef-drush'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'mysql'
cookbook 'openssl'
#cookbook 'discovery', git: 'git://github.com/hw-cookbooks/discovery.git'
#cookbook 'redis', git: 'git://github.com/miah/chef-redis.git'
#cookbook 'redisio', git: 'git://github.com/brianbianco/redisio.git'
#cookbook 'varnish'
cookbook 'postfix'
cookbook 'ark'
cookbook 'wkhtmltopdf'
cookbook 'cron'
cookbook 'aws'
cookbook 's3fs', git: 'git://github.com/sebgregoire/s3fs-recipe.git'
cookbook 'python'
cookbook 'gunicorn'
cookbook 'supervisor'
cookbook 'hipsnip-jetty'
cookbook 'hipsnip-solr'
