---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu12.04
  driver_config:
    box: precise64-dev
    url: 'https://s3.amazonaws.com/vagrant-drupal/precise64-dev.box'
 
suites:
- name: drupal7
  run_list: 
  - recipe[deploy-drupal::default]
  - recipe[drupal-solr::default]
  - recipe[minitest-handler]
  attributes: {
    "mysql": {
      "server_root_password": "root",
      "server_debian_password": "root",
      "server_repl_password": "root"
    },
    "deploy-drupal": {
      "drupal_dl_version" : "drupal-7"
    },
    "drupal-solr" : {
      "module_version" : "7.x-1.x"
    },
    "minitest" : { 
      "recipes" : ["deploy-drupal::default" , "drupal-solr::default"] ,
      "drupal_site_dir" : "/var/shared/sites/cooked.drupal/site"
    }
  }
- name: drupal6
  run_list: 
  - recipe[deploy-drupal::default]
  - recipe[drupal-solr::default]
  - recipe[minitest-handler]
  attributes: {
    "mysql": {
      "server_root_password": "root",
      "server_debian_password": "root",
      "server_repl_password": "root"
    },
    "deploy-drupal": {
      "drupal_dl_version" : "drupal-6"
    },
    "drupal-solr" : {
      "drupal_version" : "6.x-1.x"
    },
    "minitest" : { 
      "recipes" : ["deploy-drupal::default" , "drupal-solr::default"] ,
      "drupal_site_dir" : "/var/shared/sites/cooked.drupal/site"
    }

  }
